# NumPy 

NumPy (Numeric Python) is the basic library for scientific computing in Python. It provides powerful tools for **efficient handling of multi-dimensional arrays**, **linear algebra operations** and several **numerical functionalities** like Fourier-Transformation. Together with the libraries SciPy and <span style="color:red">**Matplotlib**</span>, it builts a Matlab-alike environment.

This script exemplifies the usage of NumPy by presenting some functionalities. It by far makes no claim to completeness. For a detailed documentation see https://docs.scipy.org/doc/numpy/reference/ or for a free online introduction https://www.python-course.eu/numpy.php .

In [3]:
# import numpy library - it is usually shortened with "np"
import numpy as np

---

## 1. N-dimensional Arrays
N-dimensional arrays are the backbone of NumPy. They are the blueprint for matrices. 

To use what we learned about **object-oriented programming**: Arrays are a class which can be used to create a matix object. Lets do that:

In [5]:
# create 2x5 Matrix ndarray
import numpy as np
Matrix = np.array([[8,5,7,2,1],[5,9,1,2,8]])
print(Matrix)

[[8 5 7 2 1]
 [5 9 1 2 8]]


An object of the array class is now saved in the "Matrix" variable. That means it comes with predefined attributes and methods.

At the moment our array is holding the data type integer. Can we have floats instead?

In [0]:
# create 2x5 Matrix ndarray with specified data-type
Matrix = np.array([[8,5,7,2,1],[5,9,1,2,8]], float)
print(Matrix)

In [0]:
# You can the data type attribute of the object Matrix
print(Matrix.dtype)

In [0]:
# adress index (note: in Python and thus also in NumPy, counting indices starts at 0, not 1)
print(Matrix[0,2])

In [0]:
# change value of index
Matrix[0,0] = 12
print(Matrix)

In [0]:
# adress a range of indices. E.g. the second to the fourth column of the second row
print(Matrix[1,1:3])

### Exercise

1. Create a 2x2 ndarray with values -1,2 in the first row and 7,8 in the second row and call it 'A'.

In [0]:
# place for your solution

2. Change the first value of A to 100.

In [0]:
# place for your solution

3. Create another array of your choice, called MyFirstArray of type 'int' and print it's type.

In [0]:
# place for your solution

4. Change the values of the first row of A  to 8,9 by adressing a range of indizes.

In [0]:
# place for your solution

## 2. First operations

In [6]:
# we continue with the variable Matrix from above
print(Matrix)

[[8 5 7 2 1]
 [5 9 1 2 8]]


In [7]:
# size of variable 'Matrix' is a 2x5 matrix
print(Matrix.shape)

(2, 5)


In [0]:
# memory size of array
Matrix.nbytes

In [0]:
# total number of elements in Matrix
Matrix.size

In [0]:
# transpose Matrix
Matrix = Matrix.T
print(Matrix)

In [0]:
# create range of numbers from 0-9
Numbers = np.arange(10)
print(Numbers)

In [0]:
# reshape an array
print(Numbers)
Numbers = Numbers.reshape([5,2])
print(Numbers)

Lets review **object-oriented programming**. We just used a Object - Method combination:

Numbers was created from the class array. .reshape() is a methode which is predefined for this class. 

In [0]:
# calculate the maximum value of an array
print(Numbers.max())

In [0]:
# returns the position of the minimum based on a single order numbering
Numbers.argmin()

In [0]:
# calculate the index in the array of the maximum value in the array
np.unravel_index(Numbers.argmax(),Numbers.shape)

In [0]:
# calculate sum of all elements
Numbers.sum()

In [0]:
# calculate mean value over all elements
Numbers.mean()

In [0]:
# real and imaginary part of a complex number
z = 3 +4j
print(z.real)
print(z.imag)

### Optional Exercise (if time...)

1. Print the shape of A from Exercise 1.

In [0]:
# place for your solution

2. Change A to the size 4x1.

In [0]:
# place for your solution

3. Create an array with rising values from 0 to 3 with the arange function and name it B.

In [0]:
# place for your solution

4. Add B to A and name the result C.

In [0]:
# place for your solution

5. Print C - what do you notice about it's shape?

In [0]:
# place for your solution

6. Calculate the sum and the mean of C.

In [0]:
# place for your solution

7. Print the maximum value of A as well as it's index.

In [0]:
# place for your solution

---

# 3. Linear Algebra operations

In [0]:
# create an array of ones
OneMatrix = np.ones([5,5])
print(OneMatrix)

In [0]:
# create array of random values
RandomMatrix = np.random.random([2,2])
print(RandomMatrix)

In [0]:
# create array of zeros
ZeroMatrix = np.zeros([3,5])
print(ZeroMatrix)

In [0]:
# create identity matrix
IdentityMatrix = np.eye(2)
print(IdentityMatrix)

In [0]:
# add matrices
RandomMatrix+IdentityMatrix

In [0]:
# multiply matrix with scalar
2.*IdentityMatrix

In [0]:
# multiply two matrices
RandomMatrix*IdentityMatrix

In [0]:
# multiply vector and matrix
vector = np.arange(2)
print(vector)
np.dot(RandomMatrix,vector)                   # note: when providung two vector for np.dot, the inner product ist calculated. When providing a matrix and a vector, a matrix vector multiplication is performed

In [0]:
# calculate the inverse of a matrix
np.linalg.inv(RandomMatrix)

In [0]:
# compute the eigenvalues of a matrix
np.linalg.eigvals(RandomMatrix)

In [0]:
# compute the determinant of a matrix
np.linalg.det(RandomMatrix)

In [0]:
# caluclate the inner product of two vectors
np.dot(vector,vector)    # note: when providung two vector for np.dot, the inner product ist calculated. When providing a matrix and a vector, a matrix vector multiplication is performed

In [0]:
np.cross(RandomMatrix,IdentityMatrix)

# Prepare for the following Pandas Training!

Pandas is the "Excel of Python", tha backbone of any data analysis. This will be the topic of our DS2 class.

A prerequisit to this  training is that you attend "Data Manipulation with Pandas" Free Chapter 1 "Transforming Data" https://learn.datacamp.com/courses/data-manipulation-with-pandas

You will learn what a dataframes is, learn basic editing and how to get an quick overview on large dataframes. We will build on that.